function cal_NPV=NPV_2_Var(x)
global attempt2 NPV_MATRIX
TIME_RECOMP=x(1);
RECOMP_TOP_BLOCK_DEPTH=x(2);
END_SIMULATION_TIME = 21016 - TIME_RECOMP;
OIL_TOP_COMPLETION_DEPTH=15000;
OIL_BOTTOM_COMPLETION_DEPTH =15040;
BELOW_OIL_COMPLETION = 15050;
TIME_RECOMP_str=num2str(TIME_RECOMP);
END_SIMULATION_TIME_str = num2str(END_SIMULATION_TIME);
[RECOMP_BLOCK_NO,LENGTH_RECOMPLETED_BLOCK,BELOW_OIL_BLOCK_NO, BELOW_OIL_LENGTH_BLOCK]=FUN_RECOMP_TRANSLATION_DEPTH(RECOMP_TOP_BLOCK_DEPTH,OIL_BOTTOM_COMPLETION_DEPTH,BELOW_OIL_COMPLETION);
[OIL_BOTTOM_BLOCK_NO,LENGTH_OIL_COMPLETION_BLOCK]=FUN_OIL_COMPLETION_TRANSLATION_DEPTH(OIL_TOP_COMPLETION_DEPTH,RECOMP_TOP_BLOCK_DEPTH);
TOTAL_OIL_BLOCK_NO = RECOMP_BLOCK_NO + OIL_BOTTOM_BLOCK_NO ; 
TOTAL_OIL_ZONE_BLOCK_NO = RECOMP_BLOCK_NO + OIL_BOTTOM_BLOCK_NO + BELOW_OIL_BLOCK_NO;
TOTAL_VERTICAL_BLOCK_NO = TOTAL_OIL_ZONE_BLOCK_NO + 100;
TOTAL_OIL_BLOCK_NO_str = num2str(TOTAL_OIL_BLOCK_NO);
BELOW_OIL_LENGTH_BLOCK_str = num2str(BELOW_OIL_LENGTH_BLOCK);
TOTAL_OIL_ZONE_BLOCK_NO_str = num2str(TOTAL_OIL_ZONE_BLOCK_NO);
TOTAL_VERTICAL_BLOCK_NO_str=num2str(TOTAL_VERTICAL_BLOCK_NO);
LENGTH_OIL_COMPLETION_BLOCK_str=num2str(LENGTH_OIL_COMPLETION_BLOCK);
OIL_BOTTOM_BLOCK_NO_str=num2str(OIL_BOTTOM_BLOCK_NO);
RECOMP_BLOCK_NO_str=num2str(RECOMP_BLOCK_NO + OIL_BOTTOM_BLOCK_NO);
LENGTH_RECOMPLETED_BLOCK_str=num2str(LENGTH_RECOMPLETED_BLOCK);


fid=fopen('H:\Univercity documents\master\Project\Work over\Final\Recompletion\Sensitivity Analysis\TIME\Data file\110-Z-Grids.data','r');
SCHEDULE_OUT=fread(fid);
fclose(fid);
SCHEDULE_OUT=char(SCHEDULE_OUT.');
DIMENS_edit=strfind(SCHEDULE_OUT,'DIMENS');
TIME_RECOMP_EDIT=strfind(SCHEDULE_OUT,'START RECOMPLETION TIME');
END_TIME_RECOMP_EDIT=strfind(SCHEDULE_OUT,'END RECOMPLETION TIME');
LENGTH_RECOMPLETION_EDIT=strfind(SCHEDULE_OUT,'RECOMPLETION LENGTH');
COORD=strfind(SCHEDULE_OUT,'COORDSYS');
DZ_edit=strfind(SCHEDULE_OUT,'DZLENGTH');
WELL_edit=strfind(SCHEDULE_OUT,'edit');
MULTPV=strfind(SCHEDULE_OUT,'MULTPV');

%DIMENS EDIT
SCHEDULE_OUT(DIMENS_edit+18:DIMENS_edit+20)='   ';
SCHEDULE_OUT(DIMENS_edit+18:DIMENS_edit+18+length( TOTAL_VERTICAL_BLOCK_NO_str)-1)= TOTAL_VERTICAL_BLOCK_NO_str;

%COORDSYS EDIT
SCHEDULE_OUT(COORD+22:COORD+24)='   ';
SCHEDULE_OUT(COORD+22:COORD+22+length( TOTAL_VERTICAL_BLOCK_NO_str)-1)= TOTAL_VERTICAL_BLOCK_NO_str;

%OIL COMPLETION EDIT
SCHEDULE_OUT(DZ_edit+17:DZ_edit+26)='          ';
SCHEDULE_OUT(DZ_edit+17:DZ_edit+17+length(LENGTH_OIL_COMPLETION_BLOCK_str)-1)=LENGTH_OIL_COMPLETION_BLOCK_str;
SCHEDULE_OUT(DZ_edit+44:DZ_edit+46)='   ';
SCHEDULE_OUT(DZ_edit+44:DZ_edit+44+length(OIL_BOTTOM_BLOCK_NO_str)-1)=OIL_BOTTOM_BLOCK_NO_str;
SCHEDULE_OUT(WELL_edit+26:WELL_edit+28)='   ';
SCHEDULE_OUT(WELL_edit+26:WELL_edit+26+length(TOTAL_OIL_BLOCK_NO_str)-1)=TOTAL_OIL_BLOCK_NO_str;

% OIL RECOMPLETION EDIT
SCHEDULE_OUT(DZ_edit+86:DZ_edit+88)='   ';
SCHEDULE_OUT(DZ_edit+86:DZ_edit+86+length(RECOMP_BLOCK_NO_str)-1)=RECOMP_BLOCK_NO_str ;
SCHEDULE_OUT(MULTPV+31:MULTPV+33)='   ';
SCHEDULE_OUT(MULTPV+31:MULTPV+31+length(TOTAL_OIL_ZONE_BLOCK_NO_str)-1)=TOTAL_OIL_ZONE_BLOCK_NO_str;
SCHEDULE_OUT(DZ_edit+59:DZ_edit+68)='          ';
SCHEDULE_OUT(DZ_edit+59:DZ_edit+59+length(LENGTH_RECOMPLETED_BLOCK_str)-1)=LENGTH_RECOMPLETED_BLOCK_str;
TOP_RECOMPLETION_BLOCK_NO_str=num2str(OIL_BOTTOM_BLOCK_NO + 1);
SCHEDULE_OUT(DZ_edit+81:DZ_edit+83)='   ';
SCHEDULE_OUT(DZ_edit+81:DZ_edit+81+length(TOP_RECOMPLETION_BLOCK_NO_str)-1)=TOP_RECOMPLETION_BLOCK_NO_str;
SCHEDULE_OUT(DZ_edit+103:DZ_edit+112)='          ';
SCHEDULE_OUT(DZ_edit+103:DZ_edit+103+length(BELOW_OIL_LENGTH_BLOCK_str)-1)=BELOW_OIL_LENGTH_BLOCK_str;
BELOW_OIL_BLOCK_NO_str = num2str(TOTAL_OIL_BLOCK_NO + 1); 
SCHEDULE_OUT(DZ_edit+125:DZ_edit+128)='    ';
SCHEDULE_OUT(DZ_edit+125:DZ_edit+125+length(BELOW_OIL_BLOCK_NO_str)-1)=BELOW_OIL_BLOCK_NO_str;
SCHEDULE_OUT(DZ_edit+130:DZ_edit+133)='    ';
SCHEDULE_OUT(DZ_edit+130:DZ_edit+130+length(TOTAL_OIL_ZONE_BLOCK_NO_str)-1)=TOTAL_OIL_ZONE_BLOCK_NO_str;



% Water Zone EDIT
TOP_WATER_ZONE_BLOCK_str=num2str(TOTAL_OIL_ZONE_BLOCK_NO + 1);
SCHEDULE_OUT(DZ_edit+167:DZ_edit+170)='    ';
SCHEDULE_OUT(DZ_edit+167:DZ_edit+167+length(TOP_WATER_ZONE_BLOCK_str)-1)=TOP_WATER_ZONE_BLOCK_str;
SCHEDULE_OUT(DZ_edit+172:DZ_edit+175)='    ';
SCHEDULE_OUT(DZ_edit+172:DZ_edit+172+length(TOTAL_VERTICAL_BLOCK_NO_str)-1)=TOTAL_VERTICAL_BLOCK_NO_str;




SCHEDULE_OUT(TIME_RECOMP_EDIT+35:TIME_RECOMP_EDIT+39)='     ';
SCHEDULE_OUT(TIME_RECOMP_EDIT+35:TIME_RECOMP_EDIT+35+length(TIME_RECOMP_str)-1)=TIME_RECOMP_str;
SCHEDULE_OUT(END_TIME_RECOMP_EDIT+33:END_TIME_RECOMP_EDIT+37)='     ';
SCHEDULE_OUT(END_TIME_RECOMP_EDIT+33:END_TIME_RECOMP_EDIT+33+length(END_SIMULATION_TIME_str)-1)=END_SIMULATION_TIME_str;
SCHEDULE_OUT(LENGTH_RECOMPLETION_EDIT+45:LENGTH_RECOMPLETION_EDIT+46)='  ';
SCHEDULE_OUT(LENGTH_RECOMPLETION_EDIT+45:LENGTH_RECOMPLETION_EDIT+45+length(TOP_RECOMPLETION_BLOCK_NO_str)-1)=TOP_RECOMPLETION_BLOCK_NO_str;
SCHEDULE_OUT(LENGTH_RECOMPLETION_EDIT+51:LENGTH_RECOMPLETION_EDIT+52)='  ';
SCHEDULE_OUT(LENGTH_RECOMPLETION_EDIT+51:LENGTH_RECOMPLETION_EDIT+51+length(RECOMP_BLOCK_NO_str)-1)=RECOMP_BLOCK_NO_str;
fid=fopen('H:\Univercity documents\master\Project\Work over\Final\Recompletion\Sensitivity Analysis\TIME\Data file\110-Z-Grids.data','w');
fwrite(fid,SCHEDULE_OUT);
fclose(fid);
system('"C:\ecl\macros\eclrun.exe" eclipse "H:\Univercity documents\master\Project\Work over\Final\Recompletion\Sensitivity Analysis\TIME\Data file\110-Z-Grids.data"');
[NPV,totNPV,QOP,QWp,days,WBHP,WOPT,WWCT]=cal_NPV_Well_Recom;
NPV_MATRIX(1:length(days),attempt2)=days;
NPV_MATRIX(1:length(QOP),attempt2+1)=QOP;
NPV_MATRIX(1:length(QWp),attempt2+2)=QWp;
NPV_MATRIX(1:length(NPV),attempt2+3)=WWCT;
NPV_MATRIX(1:length(NPV),attempt2+4)=WBHP;
NPV_MATRIX(1:length(NPV),attempt2+5)=WOPT;
NPV_MATRIX(1:length(NPV),attempt2+6)=NPV;
NPV_MATRIX(1:length(NPV),attempt2+7)=totNPV;
NPV_MATRIX(1:length(NPV),attempt2+8)=TIME_RECOMP;
attempt2 = attempt2 + 9;
cal_NPV=totNPV;
fclose all;
end
